name: 'GitHub Readme Guestbook'
description: 'Turn your profile readme into a guestbook where people can say thanks for your projects'
inputs:
  token:
    description: 'GitHub access token'
    required: true
  max_entries:
    description: 'Number of entries to display'
    required: true
    default: 10
runs:
  using: 'node12'
  main: 'dist/index.js'
